feat: check trigger permissions when impersonating an organization
instill-ai/pipeline-backend pull request #527
Opened 2024-06-26 10:33 UTC by jvallesm

Because

- Users can provide the `Instill-Requester-Uid` in order to trigger pipelines on
  behalf of an organization.

This commit

- Limits the execution permissions when an organization namespace is used to
  trigger a pipeline (by release or ID, sync or async). It checks:
    - User can impersonate the organization
    - If an organization is the requester and doesn't own the pipeline, either the pipeline is public or a shareable link is used.

2024-06-26 10:41 UTC, jvallesm commented
## QA ✅ 

With user A belonging to orgs A and B:

| Requester  | Owner | Sharing | Can trigger |
|:-------------:|:-------------:|:---:|:---:|
| user A      | user A     | public | Y |
| user A      | user A     | private | Y |
| user A      | org A     | public | Y |
| user A      | org A     | private | Y |
| user B      | user A     | public | Y |
| user B      | user A    | private | N |
| user B      | user A     | link | Y |
| org A      | org A     | public | Y |
| org A      | org A    | private | Y |
| org A      | user A     | public | Y |
| org A      | user A    | private | N |
| org A      | user A     | link | Y |
| org A      | org B     | public | Y |
| org A      | org B    | private | N |
| org A      | org B     | link | Y |

2024-06-26 22:56 UTC, donch1989 requested changes
A small typo, otherwise LGTM

2024-06-26 22:56 UTC, donch1989 commented on pkg/service/pipeline.go
> +	// Organizations can only trigger external private pipelines trhough a
typo

2024-06-27 05:53 UTC, donch1989 approved these changes

2024-06-27 05:55 UTC, merged