feat(pinecone): Add rerank task for Pinecone component
instill-ai/pipeline-backend pull request #773
Opened 2024-10-23 13:36 UTC by MubeenKodvavi

Because

- Rerank API is introduced from Pinecone
- Resolves instill-ai/instill-core#1114

This commit

- Added Pinecone Rerank Support. 
   - Inputs: Documents and Query input. We can restrict output to n documents by passing optional field (top-n)
   - Output: Reranked Documents and Scores
- Made URL in Pinecone Setup Optional as for rerank input URL is not required. For others, this will still need to be input.

2024-10-23 20:38 UTC, MubeenKodvavi commented
## Test Details
Tested locally by creating a pinecone component's rerank task and verified data using sample input from [API documentation](https://docs.pinecone.io/reference/api/2024-10/inference/rerank)

#### Sample Pipeline Recipe:
```
version: v1beta

variable:
  query:
    title: Query
    instill-format: string
  documents:
    title: Documents
    instill-format: array:string

component: 
  pinecone-0:
    type: pinecone
    input:
      query: ${variable.query}
      documents: ${variable.documents}
      top-n: 3
    setup:
      api-key: ${secret.pineconetoken} 
    task: TASK_RERANK

output:
  reranked_documents:
    title: Reranked Documents
    value: ${pinecone-0.output.documents}
  scores:
    title: scores
    value: ${pinecone-0.output.scores} 
```
### Input:
<img width="700" alt="image" src="https://github.com/user-attachments/assets/272a7ed4-b1ab-43f1-b2c7-3657620b6e3f">

### Component Output:
<img width="694" alt="image" src="https://github.com/user-attachments/assets/dacb4dc5-1591-41cc-b368-503f114d8cca">

2024-10-29 18:01 UTC, chuang8511 requested changes
Thanks for your contribution!

I left a few comments that we need you to modify.
And, if possible, please also help us add the test code.

2024-10-31 19:45 UTC, MubeenKodvavi commented on pkg/component/data/pinecone/v0/main.go
> +				job.Error.Error(ctx, httpclient.WrapURLError(err))
WrapURLError is a helper to add an end-user message to http transport errors.
This message is extracted in ErrorHandler interface for component job.

2024-12-04 18:13 UTC, chuang8511 approved these changes
LGTM.

2024-12-04 18:13 UTC, chuang8511 commented
@MubeenKodvavi 
I modified the code a bit. 

Will merge it when CI finishes.

Thanks for your contribution! 🙏

2024-12-06 13:01 UTC, merged