Prathamesh tugaonkar/bigquery mock server
instill-ai/pipeline-backend pull request #775
Opened 2024-10-23 16:01 UTC by PrathameshTugaonkar

Because

- Essentially because we could mock the BQ server to test it seamlessly

This commit

- tried and researched various approaches and added final approach to mock BQ server

2024-10-23 16:42 UTC, chuang8511 commented
Hi @PrathameshTugaonkar 
Thanks for your contribution.
The mock seems good.

Now, could you 
1. Please pre-commit install, you can check the lint before commit.
2. Please follow the git guideline. It is in the 3. point of [sending PR](https://github.com/instill-ai/pipeline-backend/blob/main/.github/CONTRIBUTING.md#sending-prs)
3. Please refer to [json operator test code](https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/operator/json/v0/component_test.go#L26) to increase the test code coverage. At least, we need to test
  - `func (e *execution) Execute(ctx context.Context, jobs []*base.Job) error {`
  - `func (c *component) GetDefinition(sysVars map[string]any, compConfig *base.ComponentConfig) (*pb.ComponentDefinition, error) {`

Thanks for your contribution again!

2024-10-23 17:52 UTC, PrathameshTugaonkar commented
Thanks @chuang8511  for reviewing and providing suggestions.

Is it good to go now? @chuang8511 

Point 3 - Should we take that in another ticket?

2024-10-23 18:17 UTC, chuang8511 commented
Thanks for your question!

> Point 3 - Should we take that in another ticket?

No, the issue in this ticket mainly lacks the test code for bigquery component.
And, the previous bottleneck is we don't find a good way to mock bigquery.
The end goal here is still adding test for bigquery component.

So, we will still need point 3 in this ticket!

2024-10-23 18:22 UTC, PrathameshTugaonkar commented
> Thanks for your question!
> 
> > Point 3 - Should we take that in another ticket?
> 
> No, the issue in this ticket mainly lacks the test code for bigquery component. And, the previous bottleneck is we don't find a good way to mock bigquery. The end goal here is still adding test for bigquery component.
> 
> So, we will still need point 3 in this ticket!

Okay, Definitely will work towards it. Thanks @chuang8511 !

2024-10-24 16:40 UTC, PrathameshTugaonkar commented
@chuang8511 Please review. Thanks!

2024-10-29 17:21 UTC, chuang8511 commented
Hi @PrathameshTugaonkar ,

Thanks for your contribution.

What I mean exactly is - we need to do the test like [here](https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/operator/json/v0/component_test.go#L179).

In your code, you only test bigquery http fake server. But, you don't interact the bigquery component with the bigquery http fake server.

Recently, I happened to build the similar thing. You can also take a look on [this](https://github.com/instill-ai/pipeline-backend/pull/777/files#diff-b28bb4a40ef5ea4331cf016ba72d7b0d41f80589658e2c1c20b0c0147f4c4766R39) as a reference.

2024-10-29 17:22 UTC, chuang8511 requested changes
Please check this [comment](https://github.com/instill-ai/pipeline-backend/pull/775#issuecomment-2444904136).

2024-10-29 17:22 UTC, chuang8511 commented on pkg/component/data/bigquery/v0/main_test.go
> +func TestExecute(t *testing.T) {
You need to test the interaction between the component and fake bigquery server

2024-12-04 18:03 UTC, closed without merging